CREATE TABLE room(
  room_id BIGSERIAL PRIMARY KEY,
  name VARCHAR(16) NOT NULL,
  room_number CHAR(2) NOT NULL UNIQUE,
  bed_info CHAR(2) NOT NULL
);

CREATE TABLE guest(
  guest_id BIGSERIAL PRIMARY KEY,
  first_name VARCHAR(64),
  last_name VARCHAR(64),
  email_address VARCHAR(64),
  address VARCHAR(64),
  country VARCHAR(32),
  state VARCHAR(12),
  phone_number VARCHAR(24)
);

CREATE TABLE reservation(
  reservation_id BIGSERIAL PRIMARY KEY,
  room_id BIGINT NOT NULL,
  guest_id BIGINT NOT NULL,
  res_date DATE
);

ALTER TABLE RESERVATION ADD FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID);
ALTER TABLE RESERVATION ADD FOREIGN KEY (GUEST_ID) REFERENCES GUEST(GUEST_ID);
CREATE INDEX IDX_RES_DATE_ ON RESERVATION(RES_DATE);
